### ISSUE TITLE
Automatically trim recordings

### ISSUE THREAD

**Issue by boi4** [TUM-Dev/rbg-live#7]
Hello everyone,

I'm a big fan of the new streaming site and use it for many of my lectures.
One thing that I've noticed is that most recordings seem to be turned on and off automatically which leads to big sections of silence at the beginning and end of the recorded lectures.

I think it should be possible to auto detect these sections and remove them using [ffmpeg](https://ffmpeg.org/ffmpeg-filters.html#silencedetect).

Maybe both the full and trimmed version could be hosted by the site and switched somehow.

What do you think?

**Comment by joschahenningsen** [comment]
Hi! This repo is inactive, I think you're looking for https://github.com/joschahenningsen/TUM-Live

Feel free to reopen the issue there :)

**Comment by boi4** [comment]
You may want to archive it then ;)
